WITH MAX_VIEW AS (
    SELECT  BOARD_ID
      FROM  USED_GOODS_BOARD
     WHERE  VIEWS = (SELECT  MAX(VIEWS)
                       FROM  USED_GOODS_BOARD)
)
SELECT  CONCAT(CONCAT_WS('/', '/home/grep/src', BOARD_ID, FILE_ID), FILE_NAME, FILE_EXT) AS FILE_PATH
  FROM  USED_GOODS_FILE
 WHERE  BOARD_ID = (SELECT  BOARD_ID
                      FROM  MAX_VIEW)
 ORDER
    BY  FILE_ID DESC;