# PERCENT_RANK
WITH SIZE_PERCENTILE AS (
    SELECT  ID
            ,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
      FROM  ECOLI_DATA
)
SELECT  A.ID AS ID
        ,CASE 
            WHEN B.PER <= 0.25 THEN 'CRITICAL'
            WHEN B.PER <= 0.5  THEN 'HIGH'
            WHEN B.PER <= 0.75 THEN 'MEDIUM'
            WHEN B.PER <= 1    THEN 'LOW'
          END AS COLONY_NAME
  FROM  ECOLI_DATA AS A
  LEFT
  JOIN  SIZE_PERCENTILE AS B
    ON  A.ID = B.ID
 ORDER
    BY  A.ID ASC;

# NTILE
WITH SIZE_NTILE AS (
    SELECT  ID
            ,NTILE(4) OVER (ORDER BY SIZE_OF_COLONY ASC) AS N_TILE
      FROM  ECOLI_DATA
)
SELECT  A.ID AS ID
        ,CASE
            WHEN B.N_TILE = 4 THEN 'CRITICAL'
            WHEN B.N_TILE = 3 THEN 'HIGH'
            WHEN B.N_TILE = 2 THEN 'MEDIUM'
            WHEN B.N_TILE = 1 THEN 'LOW'
          END AS COLONY_NAME
  FROM  ECOLI_DATA AS A
  LEFT
  JOIN  SIZE_NTILE AS B
    ON  A.ID = B.ID
 ORDER
    BY  A.ID ASC;