SELECT  A.WRITER_ID AS USER_ID
        ,B.NICKNAME AS NICKNAME
        ,SUM(A.PRICE) AS TOTAL_PRICE
  FROM  USED_GOODS_BOARD AS A
  LEFT
  JOIN  USED_GOODS_USER AS B
    ON  A.WRITER_ID = B.USER_ID
 WHERE  A.STATUS = 'DONE'
 GROUP
    BY  A.WRITER_ID
HAVING  TOTAL_PRICE >= 700000
 ORDER
    BY  TOTAL_PRICE ASC;