WITH GROUPED_FISH AS (
    SELECT  FISH_TYPE
            ,MAX(LENGTH) AS LENGTH
      FROM  FISH_INFO
     GROUP
        BY  FISH_TYPE
)
SELECT  C.ID
        ,B.FISH_NAME
        ,A.LENGTH
  FROM  GROUPED_FISH AS A
  LEFT
  JOIN  FISH_NAME_INFO AS B
    ON  A.FISH_TYPE = B.FISH_TYPE
  LEFT
  JOIN  FISH_INFO AS C
    ON  (A.FISH_TYPE, A.LENGTH) = (C.FISH_TYPE, C.LENGTH)
 ORDER
    BY  C.ID ASC;