WITH RENTAL_COUNT_BETWEEN_8_10 AS (
    SELECT  CAR_ID
            ,COUNT(*) AS RENTAL_COUNT
      FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE  START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
     GROUP
        BY  CAR_ID
)
SELECT  MONTH(A.START_DATE) AS MONTH
        ,A.CAR_ID AS CAR_ID
        ,COUNT(*) AS RECORDS 
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
  LEFT
  JOIN  RENTAL_COUNT_BETWEEN_8_10 AS B
    ON  A.CAR_ID = B.CAR_ID
 WHERE  B.RENTAL_COUNT >= 5
   AND  A.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
 GROUP
    BY  MONTH, CAR_ID
 ORDER
    BY  MONTH ASC
        ,CAR_ID DESC;