SELECT  A.USER_ID AS USER_ID
        ,A.NICKNAME AS NICKNAME
        ,CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS `전체주소`
        ,CONCAT_WS('-', LEFT(A.TLNO, 3), SUBSTRING(A.TLNO, 4, 4), RIGHT(A.TLNO, 4)) AS `전화번호`
  FROM  USED_GOODS_USER AS A
  LEFT
  JOIN  (SELECT  WRITER_ID
                 ,COUNT(*) AS CNT
           FROM  USED_GOODS_BOARD
          GROUP
             BY  WRITER_ID) AS B
    ON  A.USER_ID = B.WRITER_ID
 WHERE  B.CNT >= 3
 ORDER
    BY  A.USER_ID DESC;