SELECT  A.FOOD_TYPE
        ,A.REST_ID
        ,A.REST_NAME
        ,A.FAVORITES
  FROM  REST_INFO AS A
  LEFT
  JOIN  (SELECT  FOOD_TYPE
                 ,MAX(FAVORITES) AS MAX_FAV
           FROM  REST_INFO
          GROUP
             BY  FOOD_TYPE) AS B
    ON  A.FOOD_TYPE = B.FOOD_TYPE
 WHERE  A.FAVORITES = B.MAX_FAV
 ORDER
    BY  A.FOOD_TYPE DESC;