WITH GROUPED AS (
    SELECT  FISH_TYPE
            ,AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH
      FROM  FISH_INFO
     GROUP
        BY  FISH_TYPE
)
SELECT  COUNT(*) AS FISH_COUNT
        ,MAX(A.LENGTH) AS MAX_LENGTH
        ,A.FISH_TYPE AS FISH_TYPE
  FROM  FISH_INFO AS A
  LEFT
  JOIN  GROUPED AS B
    ON  A.FISH_TYPE = B.FISH_TYPE
 WHERE  B.AVG_LENGTH >= 33
 GROUP
    BY  A.FISH_TYPE
 ORDER
    BY  A.FISH_TYPE;