SELECT  A.ANIMAL_ID AS ANIMAL_ID
        ,A.NAME AS NAME
  FROM  ANIMAL_INS AS A
  LEFT
  JOIN  ANIMAL_OUTS AS B
    ON  A.ANIMAL_ID = B.ANIMAL_ID
 WHERE  B.DATETIME IS NOT NULL
 ORDER
    BY  DATEDIFF(B.DATETIME, A.DATETIME) DESC
 LIMIT  2;