WITH USER_INFO_2021 AS (
    SELECT  *
      FROM  USER_INFO
     WHERE  YEAR(JOINED) = 2021
),
ONLINE_SALE_2021 AS (
    SELECT  A.ONLINE_SALE_ID
            ,A.USER_ID
            ,A.PRODUCT_ID
            ,YEAR(A.SALES_DATE) AS YEAR
            ,MONTH(A.SALES_DATE) AS MONTH
      FROM  ONLINE_SALE AS A
     INNER
      JOIN  USER_INFO_2021 AS B
        ON  A.USER_ID = B.USER_ID
)
SELECT  YEAR
        ,MONTH
        ,COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
        ,ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO_2021), 1) AS PURCHASED_RATIO
  FROM  ONLINE_SALE_2021
 GROUP
    BY  YEAR, MONTH
 ORDER
    BY  YEAR ASC
        ,MONTH ASC;