SELECT  YEAR(A.DIFFERENTIATION_DATE) AS YEAR
        ,B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV
        ,A.ID
  FROM  ECOLI_DATA AS A
  LEFT
  JOIN  (SELECT  YEAR(DIFFERENTIATION_DATE) AS DIFF_YEAR
                 ,MAX(SIZE_OF_COLONY) AS MAX_SIZE
           FROM  ECOLI_DATA
          GROUP
             BY  DIFF_YEAR) AS B
    ON  YEAR(A.DIFFERENTIATION_DATE) = B.DIFF_YEAR
 ORDER
    BY  YEAR(A.DIFFERENTIATION_DATE) ASC
        ,YEAR_DEV ASC;