# 처음 작성한 코드
SELECT  CASE WHEN 
            DATE_FORMAT(DATETIME, '%H') LIKE '0%' THEN RIGHT(DATE_FORMAT(DATETIME, '%H'), 1)
            ELSE DATE_FORMAT(DATETIME, '%H')
        END AS HOUR
        ,COUNT(*) AS COUNT
  FROM  ANIMAL_OUTS
 WHERE  DATE_FORMAT(DATETIME, '%H') >= 9
   AND  DATE_FORMAT(DATETIME, '%H') < 20
 GROUP
    BY  HOUR
 ORDER
    BY  DATE_FORMAT(DATETIME, '%H') ASC;
    
# WHERE 절
SELECT  HOUR(DATETIME) AS HOUR
        ,COUNT(*) AS COUNT
  FROM  ANIMAL_OUTS
 WHERE  HOUR(DATETIME) BETWEEN 9 AND 19
 GROUP
    BY  HOUR
 ORDER
    BY  HOUR ASC;
    
# HAVING 절
SELECT  HOUR(DATETIME) AS HOUR
        ,COUNT(*) AS COUNT
  FROM  ANIMAL_OUTS
 GROUP
    BY  HOUR
HAVING  HOUR BETWEEN 9 AND 19
 ORDER
    BY  HOUR ASC;