# EXISTS
WITH FE_SKILL AS (
    SELECT  *
      FROM  SKILLCODES
     WHERE  CATEGORY = 'FRONT END'
)
SELECT  D.ID
        ,D.EMAIL
        ,D.FIRST_NAME
        ,D.LAST_NAME
  FROM  DEVELOPERS AS D
 WHERE  EXISTS (SELECT  1
                  FROM  FE_SKILL AS F
                 WHERE  D.SKILL_CODE & F.CODE > 0)
 ORDER
    BY  D.ID ASC;

# JOIN
WITH FRONTEND_SKILLCODES AS (
    SELECT *
      FROM SKILLCODES
     WHERE CATEGORY = 'Front End'
)
SELECT  DISTINCT D.ID
        ,D.EMAIL
        ,D.FIRST_NAME
        ,D.LAST_NAME
  FROM  DEVELOPERS AS D
  JOIN  FRONTEND_SKILLCODES AS F
    ON  D.SKILL_CODE & F.CODE
 ORDER
    BY  D.ID ASC;