WITH PRODUCT_SALES AS (
    SELECT  A.PRODUCT_ID
            ,A.PRODUCT_NAME
            ,A.PRICE * B.AMOUNT AS SALES
      FROM  FOOD_PRODUCT AS A
      LEFT
      JOIN  FOOD_ORDER AS B
        ON  A.PRODUCT_ID = B.PRODUCT_ID
     WHERE  LEFT(B.PRODUCE_DATE, 7) = '2022-05'
)
SELECT  PRODUCT_ID
        ,PRODUCT_NAME
        ,SUM(SALES) AS TOTAL_SALES
  FROM  PRODUCT_SALES
 GROUP
    BY  PRODUCT_ID
 ORDER
    BY  TOTAL_SALES DESC
        ,PRODUCT_ID ASC;