WITH GROUPED_HALF AS (
    SELECT  FLAVOR
            ,SUM(TOTAL_ORDER) AS TOTAL
      FROM  FIRST_HALF
     GROUP
        BY  FLAVOR
),
GROUPED_JULY AS (
    SELECT  FLAVOR
            ,SUM(TOTAL_ORDER) AS TOTAL
      FROM  JULY
     GROUP
        BY  FLAVOR
),
JOINED AS (
    SELECT  A.FLAVOR
            ,NULLIF(A.TOTAL, 0) + NULLIF(B.TOTAL, 0) AS TOTAL_SUM
      FROM  GROUPED_HALF AS A
      LEFT
      JOIN  GROUPED_JULY AS B
        ON  A.FLAVOR = B.FLAVOR
     ORDER
        BY  TOTAL_SUM DESC
)
SELECT  FLAVOR
  FROM  JOINED
 LIMIT  3;