WITH JOINED AS (
    SELECT  A.USER_ID
            ,A.GENDER
            ,YEAR(B.SALES_DATE) AS YEAR
            ,MONTH(B.SALES_DATE) AS MONTH
      FROM  USER_INFO AS A
     INNER
      JOIN  ONLINE_SALE AS B
        ON  A.USER_ID = B.USER_ID
)
SELECT  YEAR
        ,MONTH
        ,GENDER
        ,COUNT(DISTINCT USER_ID) AS USERS
  FROM  JOINED
 WHERE  GENDER IS NOT NULL
 GROUP
    BY  YEAR, MONTH, GENDER
 ORDER
    BY  YEAR ASC
        ,MONTH ASC
        ,GENDER ASC;