# 재귀 X
SELECT  GEN1.ID AS ID
  FROM  ECOLI_DATA AS GEN1
  LEFT
  JOIN  ECOLI_DATA AS GEN2
    ON  GEN1.PARENT_ID = GEN2.ID
  LEFT
  JOIN  ECOLI_DATA AS GEN3
    ON  GEN2.PARENT_ID = GEN3.ID
 WHERE  GEN1.PARENT_ID IS NOT NULL 
   AND  GEN2.PARENT_ID IS NOT NULL
   AND  GEN3.PARENT_ID IS NULL
 ORDER
    BY  ID ASC;

# 재귀 O
WITH RECURSIVE TBL AS (
    SELECT  ID
            ,PARENT_ID
            ,1 AS GEN
      FROM  ECOLI_DATA
     WHERE  PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT  E.ID
            ,E.PARENT_ID
            ,GEN + 1
      FROM  ECOLI_DATA AS E
     INNER
      JOIN  TBL AS T
        ON  E.PARENT_ID = T.ID
)
SELECT  ID
  FROM  TBL
 WHERE  GEN = 3
 ORDER
    BY  ID ASC;