SELECT  DISTINCT A.CART_ID AS CART_ID
  FROM  CART_PRODUCTS AS A
 INNER
  JOIN  CART_PRODUCTS AS B
    ON  A.CART_ID = B.CART_ID
 WHERE  (A.NAME = 'MILK' AND B.NAME = 'YOGURT')
    OR  (A.NAME = 'YOGURT' AND B.NAME = 'MILK')
 ORDER
    BY  CART_ID;