WITH GROUPED_MAX_PRICE AS (
    SELECT  CATEGORY
            ,MAX(PRICE) AS MAX_PRICE
      FROM  FOOD_PRODUCT
     WHERE  CATEGORY IN ('과자', '국', '김치', '식용유')
     GROUP
        BY  CATEGORY
)
SELECT  A.CATEGORY
        ,B.MAX_PRICE
        ,A.PRODUCT_NAME
  FROM  FOOD_PRODUCT AS A
  LEFT
  JOIN  GROUPED_MAX_PRICE AS B
    ON  A.CATEGORY = B.CATEGORY
 WHERE  (A.CATEGORY, A.PRICE) = (B.CATEGORY, B.MAX_PRICE)
 ORDER
    BY  B.MAX_PRICE DESC;