WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR

    UNION ALL

    SELECT HOUR+1
    FROM HOURS
    WHERE HOUR < 23
),
COUNT_BY_HOUR AS (
    SELECT  HOUR(DATETIME) AS HOUR
            ,COUNT(DISTINCT ANIMAL_ID) AS COUNT
      FROM  ANIMAL_OUTS
     GROUP
        BY  HOUR
     ORDER
        BY  HOUR ASC
)
SELECT  A.HOUR AS HOUR
        ,IFNULL(B.COUNT, 0) AS COUNT
  FROM  HOURS AS A
  LEFT
  JOIN  COUNT_BY_HOUR AS B
    ON  A.HOUR = B.HOUR;