WITH CAR AS (
    SELECT  A.HISTORY_ID
            ,A.CAR_ID
            ,DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DURATION
            ,CASE
                WHEN DATEDIFF(A.END_DATE, A.START_DATE) >= 90 THEN 90
                WHEN DATEDIFF(A.END_DATE, A.START_DATE) >= 30 THEN 30
                WHEN DATEDIFF(A.END_DATE, A.START_DATE) >= 7  THEN 7
             END AS DURATION_TYPE
            ,B.DAILY_FEE
      FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
      LEFT
      JOIN  CAR_RENTAL_COMPANY_CAR AS B
        ON  A.CAR_ID = B.CAR_ID
     WHERE  B.CAR_TYPE = '트럭'
),
TRUCK_DISCOUNT AS (
    SELECT  REPLACE(DURATION_TYPE, '일 이상', '') AS DURATION_TYPE
            ,DISCOUNT_RATE
      FROM  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE  CAR_TYPE = '트럭'
)
SELECT  A.HISTORY_ID AS HISTORY_ID
        ,ROUND(A.DAILY_FEE * (100 - IFNULL(B.DISCOUNT_RATE, 0)) / 100 * A.DURATION, 0) AS FEE
  FROM  CAR AS A
  LEFT
  JOIN  TRUCK_DISCOUNT AS B
    ON  A.DURATION_TYPE = B.DURATION_TYPE
 ORDER
    BY  FEE DESC
        ,HISTORY_ID DESC;