WITH REVIEW_COUNT_TABLE AS (
    SELECT  MEMBER_ID
            ,COUNT(REVIEW_TEXT) AS REVIEW_COUNT
      FROM  REST_REVIEW
     GROUP
        BY  MEMBER_ID
)
SELECT  B.MEMBER_NAME
        ,A.REVIEW_TEXT
        ,DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
  FROM  REST_REVIEW AS A
  LEFT
  JOIN  MEMBER_PROFILE AS B
    ON  A.MEMBER_ID = B.MEMBER_ID
  LEFT
  JOIN  REVIEW_COUNT_TABLE AS C
    ON  A.MEMBER_ID = C.MEMBER_ID
 WHERE  C.REVIEW_COUNT = (SELECT  MAX(REVIEW_COUNT)
                            FROM  REVIEW_COUNT_TABLE)
 ORDER
    BY  REVIEW_DATE ASC
        ,REVIEW_TEXT ASC;