# IS NOT NULL 사용
SELECT  ANIMAL_ID
  FROM  ANIMAL_INS
 WHERE  NAME IS NOT NULL
 ORDER
    BY  ANIMAL_ID ASC;
    
# ISNULL() 함수 사용
SELECT  ANIMAL_ID
  FROM  ANIMAL_INS
 WHERE  NOT ISNULL(NAME)
 ORDER
    BY  ANIMAL_ID ASC;