# 조건 WAREHOUSE_NAME
SELECT  WAREHOUSE_ID
        ,WAREHOUSE_NAME
        ,ADDRESS
        ,IFNULL(FREEZER_YN, 'N')
  FROM  FOOD_WAREHOUSE
 WHERE  WAREHOUSE_NAME LIKE ('%%%경기%')
 ORDER
    BY  WAREHOUSE_ID ASC;
    
# 조건 ADDRESS
SELECT  WAREHOUSE_ID
        ,WAREHOUSE_NAME
        ,ADDRESS
        ,IFNULL(FREEZER_YN, 'N')
  FROM  FOOD_WAREHOUSE
 WHERE  ADDRESS LIKE ('경기%')
 ORDER
    BY  WAREHOUSE_ID ASC;